title: Ethans Blog
author: runcible-spoon
email: ethan.noble23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Test blog description

# social links
twitter_username: jack # DO NOT include the @ character, or else the build will fail!
github_username:  runcible-spoon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
